title: ArchModule RTD
description: ArchModule using Read the Docs theme to Jekyll in my repo
remote_theme: wootaik/jekyll-theme-rtd

# Theme settings:
site_author: RealSoSy
repo_url: "https://github.com/wootaik/MyTest_Rtd"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
